### ISSUE TITLE
Error at .atom/packages/linter-jshint/node_modules/jshint-json/json.js

### ISSUE THREAD

**Issue by kfilios** [sindresorhus/jshint-json#2] opened 2016-05-16 10:25 UTC
At .atom/packages/linter-jshint/node_modules/jshint-json/json.js it crushes. The error is: "TypeError: Converting circular structure to JSON at Object". It occurs in a script where I give string to setTimeout: window.setTimeout('StatusInfo()', 100);

**Comment by Arcanemagus** [comment] 2017-05-26 16:58
To provide a bit more details:

The contents of a file to reproduce this with:
```js

setTimeout("generateOneNumber()",210);

```
Raw file: [foo.zip](https://github.com/sindresorhus/jshint-json/files/1032513/foo.zip)
_Note the blank line before `setTimeout`._

This is _not_ dependent on running inside Atom as this can be replicated on the CLI:
![image](https://cloud.githubusercontent.com/assets/427137/26504512/b7f28d62-41f9-11e7-9a30-d482da17cf30.png)

The full stack trace is:
```
                console.log(JSON.stringify({
                                 ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at reporter (C:\Users\Landon Abney\.atom\packages\linter-jshint\node_modules\jshint-json\json.js:4:20)
    at Object.run (C:\Users\Landon Abney\Documents\GitHub\linter-jshint\node_modules\jshint\src\cli.js:673:35)
    at Object.interpret (C:\Users\Landon Abney\Documents\GitHub\linter-jshint\node_modules\jshint\src\cli.js:756:18)
    at Object.<anonymous> (C:\Users\Landon Abney\Documents\GitHub\linter-jshint\node_modules\jshint\bin\jshint:3:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by Arcanemagus** [comment] 2017-05-26 17:00
...and looking over the issues this is a duplicate of #1.

**Closed as completed** 2018-03-24 17:03 UTC
